apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  project: data-engineering
  source:
    repoURL: https://googlecloudplatform.github.io/spark-on-k8s-operator
    chart: spark-operator
    targetRevision: 1.1.27
    helm:
      values: |
        sparkJobNamespace: spark-jobs
        enableWebhook: true
        enableMetrics: true
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

